name: Docker Build/Publish Image 
on:  
  push:    
    branches: [ master ]  

jobs:   
  build-docker-image:    
    runs-on: ubuntu-latest    
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:      
      - name: Checkout the code       
        uses: actions/checkout@v2
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_TOKEN}          
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eladhaim22/keepalived:${GITHUB_RUN_NUMBER}
          platforms: linux/arm/v7
